# Generated by Django 6.0 on 2026-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.AddField(
            model_name='register',
            name='area',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='fullname',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='schoolname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
